# Generated by Django 5.2.5 on 2025-08-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_description_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('diapers', 'Diapers'), ('wipes', 'Wipes'), ('toys', 'Toys'), ('clothes', 'Clothes'), ('pampers', 'Pampers'), ('Girls', 'girls'), ('Boys', 'boys'), ('Soaps', 'Soaps'), ('stroller', 'Stroller'), ('bottle', 'Bottle'), ('all', 'All Products')], default='diapers', max_length=50),
        ),
    ]
