# Generated by Django 5.2.5 on 2025-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('diapers', 'Diapers'), ('wipes', 'Wipes'), ('toys', 'Toys'), ('clothes', 'Clothes'), ('pampers', 'Pampers'), ('Girls', 'girls'), ('Boys', 'boys'), ('Soaps', 'Soaps'), ('stroller', 'Stroller'), ('bottle', 'Bottle'), ('all', 'All Products'), ('offer', 'Offers')], default='all', max_length=50),
        ),
    ]
